require(houba)
x <- as.mvector( 2**(1:3) )
inplace.inverse(x)
inplace.opposite(x)
inplace.sum(x, 0.5)
inplace.prod(x, 8)
stopifnot( all(x[] == c(0,2,3)) )

inplace.minus(x, 2)
inplace.div(x, 2)
stopifnot( all(x[] == c(-1,0,0.5)) )

x <- as.mvector( 2**(1:3) )
y <- copy(x)
inplace.prod(x, y)
inplace.sum(x, x)
inplace.div(x, y)
inplace.minus(x, y)
stopifnot( all(x[] == y[]) )
